import type { Cat } from '@/types/cat';

/** Dev-only seed cats so CatDex isn’t empty when capturing screenshots. */
export const DEMO_CATS: Cat[] = [
  {
    id: 'demo-1',
    number: 1,
    name: 'Nori',
    photoUri: '',
    latitude: 48.8642,
    longitude: 2.3971,
    discoveredAt: '2026-07-28T16:42:00.000Z',
    views: 12,
    analysis: {
      color: 'Noir',
      breed: 'Européen',
      coat: 'Court',
      description: 'Un chat noir élégant près du métro Pyrénées.',
      suggestedName: 'Nori',
      gender: 'male',
      eyes: 'Ambre',
      size: 'Moyenne',
      tags: ['Ombre', 'Mystère'],
    },
  },
  {
    id: 'demo-2',
    number: 2,
    name: 'Miette',
    photoUri: '',
    latitude: 48.8618,
    longitude: 2.4012,
    discoveredAt: '2026-07-29T09:15:00.000Z',
    views: 7,
    analysis: {
      color: 'Roux',
      breed: 'Européen',
      coat: 'Mi-long',
      description: 'Une rousse curieuse sur les marches de Belleville.',
      suggestedName: 'Miette',
      gender: 'female',
      eyes: 'Verts',
      size: 'Petite',
      tags: ['Soleil', 'Farce'],
    },
  },
  {
    id: 'demo-3',
    number: 3,
    name: 'Grisou',
    photoUri: '',
    latitude: 48.8661,
    longitude: 2.3924,
    discoveredAt: '2026-07-30T18:05:00.000Z',
    views: 4,
    analysis: {
      color: 'Gris',
      breed: 'Chartreux',
      coat: 'Court',
      description: 'Un gris posé sous un banc du square de la Butte.',
      suggestedName: 'Grisou',
      gender: 'male',
      eyes: 'Cuivre',
      size: 'Grande',
      tags: ['Calme', 'Quartier'],
    },
  },
];
