import type { Cat } from '@/types/cat';

export const DEMO_CATS: Cat[] = [
  {
    id: 'demo-1',
    number: 1,
    name: 'Ombre',
    photoUri: 'https://images.unsplash.com/photo-1574158622682-e40e69881006?w=400',
    latitude: 48.8566,
    longitude: 2.3522,
    discoveredAt: new Date().toISOString(),
    views: 12,
    notes: 'Premier chat découvert dans le quartier',
    analysis: {
      color: 'Noir',
      breed: 'Chat de gouttière',
      coat: 'Court',
      description: 'Un magnifique chat noir aux yeux dorés',
      suggestedName: 'Ombre',
      gender: 'male',
      eyes: 'Dorés',
      size: 'Moyenne',
      tags: ['Ombre', 'Mystère'],
    },
  },
  {
    id: 'demo-2',
    number: 2,
    name: 'Miel',
    photoUri: 'https://images.unsplash.com/photo-1573865526739-10c1dd1c6e95?w=400',
    latitude: 48.8566,
    longitude: 2.3522,
    discoveredAt: new Date().toISOString(),
    views: 8,
    notes: 'Chat très câlin près du parc',
    analysis: {
      color: 'Roux',
      breed: 'Européen',
      coat: 'Mi-long',
      description: 'Chat roux doux et affectueux',
      suggestedName: 'Miel',
      gender: 'female',
      eyes: 'Verts',
      size: 'Moyenne',
      tags: ['Miel', 'Câlin'],
    },
  },
  {
    id: 'demo-3',
    number: 3,
    name: 'Éclair',
    photoUri: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=400',
    latitude: 48.8566,
    longitude: 2.3522,
    discoveredAt: new Date().toISOString(),
    views: 15,
    notes: 'Chat très vif et joueur',
    analysis: {
      color: 'Tigré',
      breed: 'Bengal',
      coat: 'Court',
      description: 'Chat tigré énergique et élégant',
      suggestedName: 'Éclair',
      gender: 'male',
      eyes: 'Dorés',
      size: 'Grande',
      tags: ['Éclair', 'Vif'],
    },
  },
  {
    id: 'demo-4',
    number: 4,
    name: 'Velours',
    photoUri: 'https://images.unsplash.com/photo-1495360010541-f48722b34f7d?w=400',
    latitude: 48.8566,
    longitude: 2.3522,
    discoveredAt: new Date().toISOString(),
    views: 20,
    notes: 'Chat au pelage soyeux',
    analysis: {
      color: 'Gris',
      breed: 'Chartreux',
      coat: 'Court',
      description: 'Chat gris au pelage doux comme du velours',
      suggestedName: 'Velours',
      gender: 'female',
      eyes: 'Ambre',
      size: 'Moyenne',
      tags: ['Velours', 'Doux'],
    },
  },
];
